import db from "../src/config/db.js";

const packages = [
  // CULTURAL PACKAGES (10 packages)
  {
    name: "Classic Sri Lanka Tour",
    description: "Explore ancient cities, sacred temples, and UNESCO heritage sites across the cultural triangle.",
    fullDescription: "An immersive journey through Sri Lanka's rich cultural heritage, visiting the ancient kingdoms of Anuradhapura and Polonnaruwa, the sacred Temple of the Tooth in Kandy, and the iconic Sigiriya rock fortress.",
    price: 899,
    duration: "7 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "3-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070",
    highlights: JSON.stringify(["Sigiriya Rock Fortress", "Temple of the Tooth", "Kandy Lake", "Ancient Temples", "UNESCO Heritage Sites", "Cultural Villages"]),
    included: JSON.stringify(["Accommodation (3-star)", "Daily breakfast", "Guided tours", "Transportation", "Entrance fees", "Meals as per itinerary"]),
    excludes: JSON.stringify(["International flights", "Travel insurance", "Visa fees", "Personal expenses", "Tips and gratuities"]),
    is_active: true
  },
  {
    name: "Ancient Kingdoms Explorer",
    description: "Discover the secrets of Sri Lanka's three ancient kingdoms - Anuradhapura, Polonnaruwa, and Kandy.",
    fullDescription: "This comprehensive tour takes you back in time through three major ancient kingdoms, featuring spectacular archaeological sites, Buddhist temples, and local cultural experiences.",
    price: 799,
    duration: "6 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "3-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1588392382834-a891154bca4d?q=80&w=2070",
    highlights: JSON.stringify(["Anuradhapura Ruins", "Polonnaruwa Palace", "Kandy Temple", "Local Markets", "Spice Gardens", "Traditional Crafts"]),
    included: JSON.stringify(["3-star accommodation", "Meals (breakfast, lunch, dinner)", "Professional guide", "All entrance fees", "Local transportation"]),
    excludes: JSON.stringify(["International airfare", "Personal expenses", "Beverages (except water)", "Activities not mentioned", "Travel insurance"]),
    is_active: true
  },
  {
    name: "Spiritual Sri Lanka Journey",
    description: "Sacred temples, meditation retreats, and spiritual experiences in the heart of Sri Lanka.",
    fullDescription: "A transformative journey visiting the most sacred Buddhist temples in Sri Lanka, including meditation sessions, local monastery visits, and spiritual guidance.",
    price: 649,
    duration: "5 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=2070",
    highlights: JSON.stringify(["Sacred Temples", "Meditation Sessions", "Monastery Visits", "Buddhist Ceremonies", "Spiritual Teachings", "Prayer Rituals"]),
    included: JSON.stringify(["Basic accommodation", "Vegetarian meals", "Temple entrance fees", "Meditation classes", "Local guide"]),
    excludes: JSON.stringify(["Flights", "Non-vegetarian meals", "Travel insurance", "Personal items", "Tips"]),
    is_active: true
  },
  {
    name: "Kandy Cultural Immersion",
    description: "Deep dive into Kandy's vibrant culture with temple visits, cultural shows, and local experiences.",
    fullDescription: "Experience Kandy's rich cultural tapestry through the famous Temple of the Tooth, traditional dance performances, spice gardens, and authentic local cuisine.",
    price: 549,
    duration: "4 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "3-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Temple of the Tooth", "Kandy Lake", "Spice Plantations", "Cultural Dance Show", "Local Markets", "Arts & Crafts"]),
    included: JSON.stringify(["3-star hotel", "Meals", "Tour guide", "All entrance fees", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Personal expenses", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "UNESCO World Heritage Tour",
    description: "Visit all of Sri Lanka's UNESCO World Heritage sites in one comprehensive tour.",
    fullDescription: "An in-depth exploration of all six UNESCO World Heritage Sites including Ancient Cities, Sigiriya, Kandy Temple, Galle Fort, Sacred City, and Sinharaja Forest.",
    price: 1199,
    duration: "10 Days",
    category: "Cultural",
    budget: "luxury",
    hotel: "4-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=2070",
    highlights: JSON.stringify(["All UNESCO Sites", "Expert Historians", "Exclusive Access", "Premium Accommodations", "Fine Dining", "Private Guides"]),
    included: JSON.stringify(["4-star hotels", "All meals", "Expert guide", "All entrance fees", "Premium transfers", "Airport pickup/drop"]),
    excludes: JSON.stringify(["International flights", "Travel insurance", "Premium beverages", "Spa services", "Shopping"]),
    is_active: true
  },
  {
    name: "Traditional Arts & Crafts Tour",
    description: "Learn traditional Sri Lankan crafts from local artisans and create your own souvenirs.",
    fullDescription: "An interactive tour featuring mask-making, batik painting, pottery, wood carving, and textile weaving with hands-on workshops.",
    price: 699,
    duration: "5 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "3-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1578926078328-123456789012?q=80&w=2070",
    highlights: JSON.stringify(["Mask Making Workshop", "Batik Painting", "Pottery Class", "Weaving Demonstrations", "Artisan Visits", "Art Gallery Tour"]),
    included: JSON.stringify(["3-star accommodation", "Meals", "All workshops", "Materials", "Expert instructors", "Take-home crafts"]),
    excludes: JSON.stringify(["Flights", "Premium crafts", "Extra materials", "Personal expenses", "Tips"]),
    is_active: true
  },
  {
    name: "Colonial Heritage Trail",
    description: "Explore Sri Lanka's British colonial past through historic buildings, tea plantations, and museums.",
    fullDescription: "A nostalgic journey through colonial Sri Lanka, visiting historic hotels, colonial architecture, old railways, and heritage museums.",
    price: 849,
    duration: "6 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "4-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1464207687429-7505649dae38?q=80&w=2070",
    highlights: JSON.stringify(["Colonial Buildings", "Heritage Hotels", "Mountain Railways", "Old Forts", "Tea Plantations", "Historical Museums"]),
    included: JSON.stringify(["4-star hotels", "All meals", "Professional guide", "Museum entries", "Train rides", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Special train services", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Sigiriya & Surroundings",
    description: "Focus on the iconic Sigiriya rock fortress and its surrounding cultural sites.",
    fullDescription: "A specialized tour centered on Sigiriya, including the climb, cave temples, gardens, and nearby historical sites.",
    price: 449,
    duration: "3 Days",
    category: "Cultural",
    budget: "budget",
    hotel: "2-star",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=2070",
    highlights: JSON.stringify(["Sigiriya Climb", "Mirror Wall", "Frescoes", "Lion's Paw Entrance", "Palace Gardens", "Surrounding Temples"]),
    included: JSON.stringify(["Basic accommodation", "Meals", "Entrance fee", "Local guide", "Transportation"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Guide tip", "Extra activities", "Snacks"]),
    is_active: true
  },
  {
    name: "Buddhist Pilgrimage Path",
    description: "Follow the sacred pilgrimage sites of Buddhism across Sri Lanka.",
    fullDescription: "Visit all major Buddhist pilgrimage destinations including Sacred Foot Print, Adam's Peak, Kandy Temple, and other important religious sites.",
    price: 699,
    duration: "6 Days",
    category: "Cultural",
    budget: "budget",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=2070",
    highlights: JSON.stringify(["Sacred Footprint Temple", "Adam's Peak Pilgrimage", "Kandy Temple", "Dambulla Cave Temples", "Anuradhapura", "Local Temples"]),
    included: JSON.stringify(["Accommodation", "Vegetarian meals", "Guide", "Entrance fees", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Meat meals", "Travel insurance", "Personal items", "Tips"]),
    is_active: true
  },
  {
    name: "Sri Lankan Cuisine & Culture",
    description: "Experience Sri Lanka through its unique flavors, cooking classes, and food-centric cultural tours.",
    fullDescription: "A gastronomic adventure combining cooking classes, market tours, spice plantation visits, and traditional family dinners.",
    price: 749,
    duration: "5 Days",
    category: "Cultural",
    budget: "mid",
    hotel: "3-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?q=80&w=2070",
    highlights: JSON.stringify(["Cooking Classes", "Market Tours", "Spice Plantations", "Family Dinners", "Food Demonstrations", "Taste Tests"]),
    included: JSON.stringify(["3-star accommodation", "All cooking classes", "Market tours", "Meals (prepared in classes)", "Expert chefs", "Recipes"]),
    excludes: JSON.stringify(["Flights", "Drinks", "Travel insurance", "Extra meals outside program", "Tips"]),
    is_active: true
  },

  // BEACH PACKAGES (10 packages)
  {
    name: "Beaches Paradise Escape",
    description: "Relax on pristine beaches, enjoy water sports, and experience island luxury.",
    fullDescription: "A tropical paradise escape featuring white-sand beaches, crystal-clear waters, and luxury beach resorts.",
    price: 899,
    duration: "5 Days",
    category: "Beach",
    budget: "mid",
    hotel: "4-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2070",
    highlights: JSON.stringify(["Sandy Beaches", "Water Sports", "Snorkeling", "Beach Resorts", "Sunset Cruises", "Swimming"]),
    included: JSON.stringify(["4-star beachfront hotel", "All meals", "Beach activities", "Snorkeling equipment", "Transfers", "Daily breakfast"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium water sports", "Spa treatments", "Tips"]),
    is_active: true
  },
  {
    name: "Luxury Beach & Spa Retreat",
    description: "Ultimate luxury beachfront experience with world-class spa treatments and fine dining.",
    fullDescription: "An exclusive resort experience combining pristine beaches, championship spa services, gourmet dining, and water activities.",
    price: 1299,
    duration: "4 Days",
    category: "Beach",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=2070",
    highlights: JSON.stringify(["5-Star Resort", "World-Class Spa", "Gourmet Dining", "Beach Club", "Water Sports", "Sunset Dinners"]),
    included: JSON.stringify(["5-star luxury resort", "All meals (fine dining)", "Unlimited spa treatments", "Water sports", "Concierge", "Airport transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Special events", "Premium wine", "Shopping"]),
    is_active: true
  },
  {
    name: "Mirissa Beach & Whale Watching",
    description: "Relax in Mirissa's charming beach town and experience whale watching tours.",
    fullDescription: "A beachside experience in the popular Mirissa town with boat tours for whale and dolphin watching, night fishing, and beach relaxation.",
    price: 649,
    duration: "4 Days",
    category: "Beach",
    budget: "mid",
    hotel: "3-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1583452122519-92c99b59fb3c?q=80&w=2070",
    highlights: JSON.stringify(["Whale Watching", "Dolphin Spotting", "Night Fishing", "Beach Relaxation", "Local Food", "Sunset Views"]),
    included: JSON.stringify(["3-star beach hotel", "Meals", "Whale watching tour", "Fishing trip", "Guide", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium tours", "Meals outside package", "Tips"]),
    is_active: true
  },
  {
    name: "Unawatuna Coastal Charm",
    description: "Discover the laid-back charm of Unawatuna beach with water sports and cultural sites nearby.",
    fullDescription: "A relaxing beach holiday in picturesque Unawatuna with easy access to Galle Fort, water sports, and coastal dining.",
    price: 549,
    duration: "3 Days",
    category: "Beach",
    budget: "budget",
    hotel: "3-star",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1551028719-00167b16ebc5?q=80&w=2070",
    highlights: JSON.stringify(["Sandy Beach", "Galle Fort Nearby", "Water Sports", "Local Restaurants", "Swimming", "Coral Reefs"]),
    included: JSON.stringify(["3-star accommodation", "Meals", "Snorkeling equipment", "Guide for Galle Fort", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium activities", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Bentota Beach Resort Experience",
    description: "Experience luxury at Bentota with water sports, river safaris, and pristine beaches.",
    fullDescription: "A sophisticated beach experience featuring upscale resorts, thrilling water sports, lagoon safaris, and palm-fringed beaches.",
    price: 899,
    duration: "5 Days",
    category: "Beach",
    budget: "mid",
    hotel: "4-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070",
    highlights: JSON.stringify(["Bentota Resort", "River Safari", "Water Sports", "Jet Skiing", "Beach Bar", "Spa"]),
    included: JSON.stringify(["4-star resort", "All meals", "Water sports equipment", "River safari", "Beach access", "Daily breakfast"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium water sports", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Negombo Beach & Lagoon Tour",
    description: "Explore Negombo's famous lagoon with fishing villages and beach relaxation.",
    fullDescription: "A short beach getaway focusing on traditional fishing villages, lagoon cruises, and beach activities near Colombo.",
    price: 399,
    duration: "2 Days",
    category: "Beach",
    budget: "budget",
    hotel: "2-star",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?q=80&w=2070",
    highlights: JSON.stringify(["Lagoon Cruise", "Fishing Village", "Beach Walk", "Local Market", "Water Sports", "Fish Market"]),
    included: JSON.stringify(["2-star accommodation", "Meals", "Lagoon tour", "Guide", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Boat tips", "Meals outside", "Activities"]),
    is_active: true
  },
  {
    name: "Arugam Bay Surfing Paradise",
    description: "Perfect for surfers with legendary waves, beach culture, and laid-back vibes.",
    fullDescription: "A surfer's dream destination with world-class waves, surf schools, beach parties, and coastal relaxation.",
    price: 699,
    duration: "5 Days",
    category: "Beach",
    budget: "budget",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?q=80&w=2070",
    highlights: JSON.stringify(["Surfing Lessons", "Legendary Waves", "Beach Parties", "Nightlife", "Laid-Back Vibe", "Local Cafes"]),
    included: JSON.stringify(["Beach accommodation", "Meals", "Surfboard rental", "Lessons", "Guide"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Equipment purchase", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "South Coast Beach Hopping",
    description: "Visit multiple beaches along the south coast - Mirissa, Unawatuna, Matara, and Dondra Head.",
    fullDescription: "An exciting multi-beach tour covering the best of south coast attractions, from bustling beaches to quiet coves.",
    price: 749,
    duration: "5 Days",
    category: "Beach",
    budget: "mid",
    hotel: "3-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2070",
    highlights: JSON.stringify(["Multiple Beaches", "Beach Hopping", "Water Sports", "Local Markets", "Sunset Views", "Coastal Villages"]),
    included: JSON.stringify(["3-star accommodation", "Meals", "All transfers", "Beach activities", "Guide"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium activities", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Maldives Day Trip from Sri Lanka",
    description: "Exclusive speedboat adventure to nearby Maldives with snorkeling and island exploration.",
    fullDescription: "A thrilling day-long escape to Maldivian islands with snorkeling in pristine reefs and island exploration.",
    price: 399,
    duration: "1 Day",
    category: "Beach",
    budget: "mid",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=2070",
    highlights: JSON.stringify(["Island Exploration", "Snorkeling", "Tropical Fish", "Speedboat", "Lunch on Island", "Photo Opportunities"]),
    included: JSON.stringify(["Speedboat transfer", "Lunch", "Snorkeling gear", "Guide", "Island entry"]),
    excludes: JSON.stringify(["Flights to Sri Lanka", "Hotel", "Travel insurance", "Personal items", "Tips"]),
    is_active: true
  },
  {
    name: "Island Hopping & Water Sports",
    description: "Active beach holiday with water sports, island exploring, and diving opportunities.",
    fullDescription: "An action-packed beach experience combining snorkeling, scuba diving, surfing, and island exploration.",
    price: 849,
    duration: "6 Days",
    category: "Beach",
    budget: "mid",
    hotel: "3-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2070",
    highlights: JSON.stringify(["Scuba Diving", "Snorkeling", "Island Hopping", "Water Sports", "Diving Certification", "Coral Reefs"]),
    included: JSON.stringify(["3-star accommodation", "Meals", "Water sports equipment", "Diving lessons", "Island tours", "Guide"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Diving certification fee", "Premium lessons", "Tips"]),
    is_active: true
  },

  // WILDLIFE PACKAGES (10 packages)
  {
    name: "Wildlife Safari Adventure",
    description: "Experience Sri Lanka's incredible wildlife in its natural habitat with expert guides.",
    fullDescription: "Thrilling safari adventures in national parks featuring leopards, elephants, buffalo, and countless bird species.",
    price: 999,
    duration: "5 Days",
    category: "Wildlife",
    budget: "mid",
    hotel: "3-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=2070",
    highlights: JSON.stringify(["Leopard Spotting", "Elephant Herds", "Bird Watching", "Safari Drives", "Expert Naturalists", "Wildlife Photography"]),
    included: JSON.stringify(["3-star accommodation", "Meals", "Safari drives", "Expert guide", "Binoculars", "Transportation"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Photography equipment", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Yala National Park Safari",
    description: "Sri Lanka's largest national park with highest leopard density and abundant wildlife.",
    fullDescription: "Dedicated safari experience in Yala with multiple safari drives, expert wildlife guides, and comfortable safari lodges.",
    price: 899,
    duration: "4 Days",
    category: "Wildlife",
    budget: "mid",
    hotel: "3-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1437622368535-7e0a2cb8f3b0?q=80&w=2070",
    highlights: JSON.stringify(["Leopard Safari", "Elephant Herds", "Buffalo", "Crocodiles", "Bird Species", "Early Morning Drives"]),
    included: JSON.stringify(["Safari lodge", "Meals", "Multiple safari drives", "Professional guide", "Binoculars"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium photo tours", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Udawalawe Elephant Safari",
    description: "Close encounters with Sri Lankan elephants in Udawalawe National Park with expert wildlife guides.",
    fullDescription: "Intimate elephant viewing experiences with a focus on conservation and understanding elephant behavior.",
    price: 749,
    duration: "3 Days",
    category: "Wildlife",
    budget: "mid",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1474349929302-8e7098ae2e0f?q=80&w=2070",
    highlights: JSON.stringify(["Elephant Herds", "Safari Drives", "Waterhole Visits", "Young Calves", "Veterinary Support", "Conservation Learning"]),
    included: JSON.stringify(["Simple accommodation", "Meals", "Safari drives", "Wildlife guide", "Entrance fee"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium lodges", "Alcohol", "Tips"]),
    is_active: true
  },
  {
    name: "Sinharaja Rainforest Trek",
    description: "Explore Sri Lanka's only remaining rainforest with unique endemic species and biodiversity.",
    fullDescription: "An immersive trekking experience through UNESCO-listed rainforest with expert naturalists studying flora and fauna.",
    price: 599,
    duration: "3 Days",
    category: "Wildlife",
    budget: "budget",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2070",
    highlights: JSON.stringify(["Rainforest Trek", "Endemic Birds", "Wildlife Spotting", "Waterfall Hikes", "Natural Pool", "Ecological Learning"]),
    included: JSON.stringify(["Basic accommodation", "Meals", "Expert guide", "Entrance fee", "Trek equipment"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Luxury lodges", "Meals outside program", "Tips"]),
    is_active: true
  },
  {
    name: "Bird Watching Paradise",
    description: "Paradise for bird watchers with over 250 endemic and migratory bird species.",
    fullDescription: "Comprehensive bird watching tour across multiple ecosystems - parks, wetlands, and forests with expert ornithologists.",
    price: 699,
    duration: "5 Days",
    category: "Wildlife",
    budget: "budget",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1444464666175-1642321dd308?q=80&w=2070",
    highlights: JSON.stringify(["Eagle Watching", "Endemic Birds", "Wetland Birds", "Migratory Species", "Photography Hides", "Naturalist Guides"]),
    included: JSON.stringify(["Simple accommodation", "Meals", "Multiple locations", "Expert guide", "Binoculars"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium lodges", "Camera equipment", "Tips"]),
    is_active: true
  },
  {
    name: "Horton Plains & Wildlife Trek",
    description: "High altitude trekking combined with wildlife spotting and scenic mountain views.",
    fullDescription: "Challenging trek through Horton Plains with unique highland fauna, World's End viewpoint, and Baker's Falls.",
    price: 549,
    duration: "2 Days",
    category: "Wildlife",
    budget: "budget",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["World's End View", "Baker's Falls", "High Altitude Trek", "Sambar Deer", "Endemic Flowers", "Mountain Views"]),
    included: JSON.stringify(["Basic accommodation", "Meals", "Guide", "Entrance fee", "Trek equipment"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium lodges", "Meals outside", "Tips"]),
    is_active: true
  },
  {
    name: "Marine Life & Diving Expedition",
    description: "Underwater adventures exploring coral reefs, tropical fish, and marine ecosystems.",
    fullDescription: "Diving expedition to pristine reefs with encounters with diverse marine species and coral gardens.",
    price: 749,
    duration: "4 Days",
    category: "Wildlife",
    budget: "mid",
    hotel: "3-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=2070",
    highlights: JSON.stringify(["Scuba Diving", "Coral Reefs", "Tropical Fish", "Sea Turtles", "Octopus", "Underwater Photography"]),
    included: JSON.stringify(["3-star accommodation", "Meals", "Diving equipment", "Instructor", "Certification help"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Certification fee", "Camera equipment", "Tips"]),
    is_active: true
  },
  {
    name: "Reptile & Amphibian Discovery",
    description: "Specialized tour focusing on snakes, lizards, amphibians, and reptile conservation.",
    fullDescription: "Educational adventure with herpetologists studying Sri Lanka's diverse reptile species and their habitats.",
    price: 649,
    duration: "4 Days",
    category: "Wildlife",
    budget: "budget",
    hotel: "2-star",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1444464666175-1642321dd308?q=80&w=2070",
    highlights: JSON.stringify(["Reptile Study", "Snake Encounters", "Lizard Species", "Frog Watching", "Conservation Talk", "Night Walks"]),
    included: JSON.stringify(["Basic accommodation", "Meals", "Herpetologist guide", "Research areas access", "Education materials"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium research", "Special accommodations", "Tips"]),
    is_active: true
  },
  {
    name: "Whale & Dolphin Watching",
    description: "Seasonal boat tours to spot blue whales, sperm whales, and playful dolphins.",
    fullDescription: "Thrilling marine expeditions chasing whale migrations and dolphin pods along Sri Lankan waters.",
    price: 599,
    duration: "2 Days",
    category: "Wildlife",
    budget: "mid",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1583452122519-92c99b59fb3c?q=80&w=2070",
    highlights: JSON.stringify(["Blue Whales", "Sperm Whales", "Dolphins", "Boat Expeditions", "Marine Biology", "Photography"]),
    included: JSON.stringify(["Beach accommodation", "Meals", "Boat tour", "Marine biologist guide", "Binoculars"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Special tours", "Meals outside", "Tips"]),
    is_active: true
  },

  // ADVENTURE PACKAGES (10 packages)
  {
    name: "Adventure & Nature Escape",
    description: "Thrilling activities including rock climbing, canyoning, and jungle trekking.",
    fullDescription: "An action-packed adventure combining multiple adrenaline-pumping activities in Sri Lanka's wild landscapes.",
    price: 699,
    duration: "5 Days",
    category: "Adventure",
    budget: "mid",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1568219656418-15c329312bf1?q=80&w=2070",
    highlights: JSON.stringify(["Rock Climbing", "Canyoning", "Jungle Trek", "Whitewater Rafting", "Rock Rappelling", "Nature Camping"]),
    included: JSON.stringify(["Basic accommodation", "Meals", "All equipment", "Expert guides", "Safety gear"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Professional training", "Premium equipment", "Tips"]),
    is_active: true
  },
  {
    name: "Mountain Climbing Challenge",
    description: "Challenging climbs of Sri Lanka's highest peaks including Adam's Peak and Pidurutalagala.",
    fullDescription: "Summit experiences on sacred and scenic peaks with early morning climbs and panoramic views.",
    price: 449,
    duration: "3 Days",
    category: "Adventure",
    budget: "budget",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2070",
    highlights: JSON.stringify(["Adam's Peak Climb", "Pidurutalagala", "Sunrise Views", "Pilgrimage Trails", "Mountain Huts", "Sacred Sites"]),
    included: JSON.stringify(["Simple accommodation", "Meals", "Guide", "Walking equipment"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium lodges", "Professional guide", "Tips"]),
    is_active: true
  },
  {
    name: "Whitewater Rafting Thrills",
    description: "Grade 3-4 whitewater rafting on river rapids with professional instructors.",
    fullDescription: "Exciting rafting expeditions on multiple rivers with varying difficulty levels and scenic canyon views.",
    price: 399,
    duration: "1-2 Days",
    category: "Adventure",
    budget: "budget",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Grade 3-4 Rapids", "River Thrills", "Professional Instructors", "Safety Equipment", "Scenic Views", "Group Adventure"]),
    included: JSON.stringify(["Accommodation", "Meals", "Raft rental", "Guide", "Safety gear"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Professional photos", "Extra meals", "Tips"]),
    is_active: true
  },
  {
    name: "Jungle Trekking Expedition",
    description: "Multi-day jungle treks through remote wilderness with camping and wildlife encounters.",
    fullDescription: "Off-the-beaten-path jungle exploration with wilderness camping, wildlife spotting, and survival skills.",
    price: 749,
    duration: "5 Days",
    category: "Adventure",
    budget: "budget",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2070",
    highlights: JSON.stringify(["Jungle Trek", "Wilderness Camping", "Wildlife Spotting", "River Crossing", "Survival Skills", "Remote Villages"]),
    included: JSON.stringify(["Camping supplies", "Meals", "Expert guide", "Trekking equipment", "First aid"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium camping", "Meals outside", "Tips"]),
    is_active: true
  },
  {
    name: "Paragliding & Aerial Adventures",
    description: "Tandem paragliding flights offering stunning aerial views of Sri Lankan landscapes.",
    fullDescription: "Thrilling paragliding experiences from scenic launch points with professional pilots and safety training.",
    price: 599,
    duration: "3 Days",
    category: "Adventure",
    budget: "mid",
    hotel: "2-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Tandem Paragliding", "Aerial Views", "Mountain Launch", "Photography", "Adrenaline Rush", "Scenic Routes"]),
    included: JSON.stringify(["Accommodation", "Meals", "Paragliding flights", "Pilot", "Safety gear"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Video recording", "Professional photos", "Tips"]),
    is_active: true
  },
  {
    name: "Rock Climbing School",
    description: "Beginner to advanced rock climbing courses on natural rock formations.",
    fullDescription: "Comprehensive climbing training on various rock types with certified instructors and all safety equipment.",
    price: 649,
    duration: "4 Days",
    category: "Adventure",
    budget: "mid",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Rock Climbing", "Climbing Instruction", "Different Routes", "Certification", "Safety Training", "Equipment Mastery"]),
    included: JSON.stringify(["Simple accommodation", "Meals", "All climbing equipment", "Certified instructor", "Training materials"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Professional certification", "Equipment purchase", "Tips"]),
    is_active: true
  },
  {
    name: "Canyoning & Waterfall Rappel",
    description: "Exciting canyoning adventures featuring waterfall rappelling and creek exploration.",
    fullDescription: "Technical canyoning expedition with waterfall descents, natural pools, and canyon trekking.",
    price: 549,
    duration: "2 Days",
    category: "Adventure",
    budget: "mid",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Waterfall Rappel", "Canyon Trek", "Swimming Pools", "Rope Techniques", "Adrenaline", "Nature"]),
    included: JSON.stringify(["Accommodation", "Meals", "Canyoning gear", "Guide", "Safety equipment"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Professional guides", "Meals outside", "Tips"]),
    is_active: true
  },
  {
    name: "Mountain Biking Trail Tour",
    description: "Off-road mountain biking on trails through forests, villages, and mountains.",
    fullDescription: "Scenic bike tours traversing varied terrain from easy paths to challenging single tracks.",
    price: 499,
    duration: "3 Days",
    category: "Adventure",
    budget: "budget",
    hotel: "2-star",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Mountain Biking", "Trail Routes", "Forest Paths", "Village Routes", "Mountain Descents", "Scenic Views"]),
    included: JSON.stringify(["Accommodation", "Meals", "Mountain bike", "Guide", "Repair kit"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Professional training", "Premium bikes", "Tips"]),
    is_active: true
  },
  {
    name: "Zip Line Forest Adventure",
    description: "Thrilling zip lining through forest canopies with multiple lines and platforms.",
    fullDescription: "Forest canopy zip line course with platforms, bridges, and aerial activities.",
    price: 399,
    duration: "1 Day",
    category: "Adventure",
    budget: "budget",
    hotel: "2-star",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=2070",
    highlights: JSON.stringify(["Zip Lining", "Canopy Views", "Multiple Lines", "Adventure Platforms", "Adrenaline", "Safety Harness"]),
    included: JSON.stringify(["Day trip", "Meals", "Zip line course", "Safety equipment", "Guide"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Photos/video", "Extra activities", "Tips"]),
    is_active: true
  },

  // LUXURY PACKAGES (10 packages)
  {
    name: "Premium Sri Lanka Odyssey",
    description: "Ultra-luxury 10-day journey combining culture, nature, and exclusive experiences.",
    fullDescription: "Comprehensive luxury tour with 5-star accommodations, private guides, exclusive activities, and fine dining throughout.",
    price: 2499,
    duration: "10 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=2070",
    highlights: JSON.stringify(["5-Star Resorts", "Private Guides", "Exclusive Experiences", "Fine Dining", "Spa & Wellness", "VIP Treatment"]),
    included: JSON.stringify(["Luxury accommodations", "All meals (gourmet)", "Private guides", "Premium transfers", "Activities", "Concierge service"]),
    excludes: JSON.stringify(["International flights", "Travel insurance", "Premium shopping", "Special events", "Charity donations"]),
    is_active: true
  },
  {
    name: "Exclusive Private Villa Retreat",
    description: "Stay in exclusive private villas with personal chefs, staff, and bespoke itineraries.",
    fullDescription: "Ultimate privacy and luxury with private villa accommodations, personalized service, and customized activities.",
    price: 1999,
    duration: "7 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070",
    highlights: JSON.stringify(["Private Villa", "Personal Chef", "Dedicated Staff", "Bespoke Itinerary", "Luxury Amenities", "Privacy"]),
    included: JSON.stringify(["Luxury private villa", "Meals (prepared daily)", "Personal chef", "House staff", "Private transfers", "Activities"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Special events", "Alcohol (premium)", "Gratuities"]),
    is_active: true
  },
  {
    name: "Wellness & Spa Luxury Retreat",
    description: "Holistic wellness experience with luxury spa treatments, yoga, and healthy cuisine.",
    fullDescription: "Transformative wellness journey combining Ayurvedic treatments, meditation, yoga, and organic cuisine.",
    price: 1699,
    duration: "7 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1544161515-81aae3ff8744?q=80&w=2070",
    highlights: JSON.stringify(["Ayurvedic Spa", "Daily Yoga", "Meditation", "Organic Meals", "Wellness Coaching", "Luxury Resort"]),
    included: JSON.stringify(["5-star resort", "All meals (organic)", "Daily spa treatments", "Yoga classes", "Meditation", "Wellness guidance"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium treatments", "Alcohol", "Shopping"]),
    is_active: true
  },
  {
    name: "Golf & Luxury Resort Experience",
    description: "Exclusive golf resort with championship courses, five-star amenities, and gourmet dining.",
    fullDescription: "Premium golfing vacation at Sri Lanka's finest golf courses with luxury resort accommodations.",
    price: 1899,
    duration: "5 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=2070",
    highlights: JSON.stringify(["Championship Golf", "5-Star Resort", "Spa & Wellness", "Fine Dining", "Golf Instruction", "Country Club"]),
    included: JSON.stringify(["5-star resort", "Golf rounds", "Clubhouse access", "Meals (gourmet)", "Golf instruction", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Pro shop items", "Premium wines", "Gratuities"]),
    is_active: true
  },
  {
    name: "Private Yacht Cruise Experience",
    description: "Luxury yacht charter along Sri Lanka's coast with snorkeling and exclusive island stops.",
    fullDescription: "Exclusive sailing experience visiting secluded islands, snorkeling sites, and coastal towns from a private yacht.",
    price: 1799,
    duration: "5 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1552632355-cb50515932c7?q=80&w=2070",
    highlights: JSON.stringify(["Luxury Yacht", "Private Crew", "Island Hopping", "Snorkeling", "Gourmet Dining", "Water Sports"]),
    included: JSON.stringify(["Luxury yacht", "Meals (gourmet)", "Crew service", "Snorkeling equipment", "Island visits", "Water sports"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium beverages", "Helicopter tours", "Gratuities"]),
    is_active: true
  },
  {
    name: "Heritage Luxury Tour",
    description: "Opulent exploration of Sri Lankan heritage in luxury accommodations with expert historians.",
    fullDescription: "Elevated cultural journey with luxury hotels, expert historians, exclusive access, and fine dining experiences.",
    price: 1599,
    duration: "8 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2070",
    highlights: JSON.stringify(["Luxury Hotels", "Expert Historians", "Exclusive Access", "Fine Dining", "Private Guides", "VIP Treatment"]),
    included: JSON.stringify(["5-star hotels", "Meals (gourmet)", "Expert historian guide", "All entrance fees", "Exclusive access", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium shopping", "Alcohol", "Gratuities"]),
    is_active: true
  },
  {
    name: "Adventure Luxury Combination",
    description: "Luxury accommodations combined with thrilling adventure activities and professional guides.",
    fullDescription: "Premium adventure experience with luxury base camps, expert guides, and adrenaline activities.",
    price: 1499,
    duration: "6 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "4-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=2070",
    highlights: JSON.stringify(["Luxury Camps", "Adventure Activities", "Expert Guides", "Premium Meals", "Safety Equipment", "Concierge"]),
    included: JSON.stringify(["Luxury accommodation", "All meals", "Adventure activities", "Professional guides", "Equipment", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium activities", "Alcohol", "Gratuities"]),
    is_active: true
  },
  {
    name: "Romantic Honeymoon Package",
    description: "Perfect honeymoon experience with romantic dinners, sunset activities, and couple spa treatments.",
    fullDescription: "Specially curated romantic experience with couples activities, private dinners, and luxury accommodations.",
    price: 1699,
    duration: "7 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=2070",
    highlights: JSON.stringify(["Romantic Dinners", "Couple Spa", "Sunset Activities", "Private Beaches", "Wine Tasting", "Photography"]),
    included: JSON.stringify(["Luxury resort", "Romantic dinners", "Couple spa treatments", "Beach activities", "Bottle of wine", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium wine", "Photos/video", "Gratuities"]),
    is_active: true
  },
  {
    name: "Family Luxury Vacation",
    description: "All-inclusive family package with kid-friendly activities in luxury resorts and entertainment.",
    fullDescription: "Family-focused luxury vacation with activities for all ages, kids clubs, and safe adventure experiences.",
    price: 1899,
    duration: "7 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2070",
    highlights: JSON.stringify(["Family Activities", "Kids Club", "Water Sports", "Spa", "Fine Dining", "Safe Adventures"]),
    included: JSON.stringify(["5-star resort", "All meals", "Kids programs", "Family activities", "Water sports", "Entertainment"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium services", "Shopping", "Gratuities"]),
    is_active: true
  },
  {
    name: "Corporate Retreat Package",
    description: "Team building and incentive retreat with conference facilities, outdoor activities, and fine dining.",
    fullDescription: "Custom corporate package with team-building activities, meeting facilities, wellness programs, and luxury accommodations.",
    price: 2299,
    duration: "4 Days",
    category: "Luxury",
    budget: "luxury",
    hotel: "5-star",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070",
    highlights: JSON.stringify(["Team Building", "Conference Room", "Outdoor Activities", "Fine Dining", "Spa & Wellness", "Transport"]),
    included: JSON.stringify(["Luxury resort", "All meals", "Meeting facilities", "Team activities", "Wellness", "Transfers"]),
    excludes: JSON.stringify(["Flights", "Travel insurance", "Premium services", "Alcohol", "Gratuities"]),
    is_active: true
  }
];

async function seedPackages() {
  try {
    console.log("🌱 Starting package seed...");

    for (const pkg of packages) {
      const result = await db.query(
        `INSERT INTO tour_packages 
        (name, description, full_description, highlights, includes, excludes, price, duration, category, budget, hotel, rating, image, is_active)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
        RETURNING package_id`,
        [
          pkg.name,
          pkg.description,
          pkg.fullDescription,
          pkg.highlights,
          pkg.included,
          pkg.excludes,
          pkg.price,
          pkg.duration,
          pkg.category,
          pkg.budget,
          pkg.hotel,
          pkg.rating,
          pkg.image,
          pkg.is_active
        ]
      );

      console.log(`✅ ${pkg.name} (${pkg.category}) - ID: ${result.rows[0].package_id}`);
    }

    console.log(`\n🎉 Successfully seeded ${packages.length} packages!`);

    // Get statistics
    const stats = await db.query(`
      SELECT category, COUNT(*) as count, AVG(price) as avg_price
      FROM tour_packages
      WHERE is_active = true
      GROUP BY category
      ORDER BY category
    `);

    console.log("\n📊 Package Statistics:");
    console.log(stats.rows);

  } catch (error) {
    console.error("❌ Seeding error:", error);
    process.exit(1);
  }
}

seedPackages();
